steps:
  - id: Running unit tests
    name: 'gcr.io/cloud-builders/go'
    env:
      - GOPATH=
    args: ['rm -rf $GOPATH/go.mod', '&&', test','./...']
  - id: Building go lang image
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-ci-challenge', '.']
images: ['gcr.io/$PROJECT_ID/go-ci-challenge']
